name: PR Build Check

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache SourceMod dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            sourcemod-*
          key: ${{ runner.os }}-sourcemod-${{ hashFiles('**/sourcemod-*.tar.gz') }}
          restore-keys: |
            ${{ runner.os }}-sourcemod-

      - name: Download Sourcemod
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://sm.alliedmods.net/smdrop/1.11/sourcemod-1.11.0-git6968-linux.tar.gz

      - name: Setup SourceMod
        run: |
          tar -xzf sourcemod-*.tar.gz
          git clone https://github.com/Bara/Multi-Colors.git
          git clone https://github.com/SilvDev/Left4DHooks.git

      - name: Build plugin
        id: build
        run: |
          mkdir -p build
          addons/sourcemod/scripting/spcomp64 l4d2_tank_draw/scripting/l4d2_tank_draw.sp -o build/l4d2_tank_draw.smx -i ./Multi-Colors/addons/sourcemod/scripting/include -i ./Left4DHooks/sourcemod/scripting/include
          addons/sourcemod/scripting/spcomp64 l4d2_tank_trigger/scripting/l4d2_tank_trigger.sp -o build/l4d2_tank_trigger.smx -i ./Multi-Colors/addons/sourcemod/scripting/include -i ./Left4DHooks/sourcemod/scripting/include

      - name: Check build success
        run: |
          if [ -f "build/l4d2_tank_draw.smx" ] && [ -f "build/l4d2_tank_trigger.smx" ]; then
            echo "Build successful!"
          else
            echo "Build failed - not all plugins were compiled"
            exit 1
          fi
