name: Build SourceMod Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SourceMod
        run: |
          wget https://sm.alliedmods.net/smdrop/1.11/sourcemod-1.11.0-git6968-linux.tar.gz
          tar -xzf sourcemod-*.tar.gz
          git clone https://github.com/Bara/Multi-Colors.git

      - name: Build plugin
        run: |
          mkdir -p build
          addons/sourcemod/scripting/spcomp64 l4d2_tank_draw/scripting/l4d2_tank_draw.sp -o build/l4d2_tank_draw.smx -i ./Multi-Colors/addons/sourcemod/scripting/include
          addons/sourcemod/scripting/spcomp64 l4d2_tank_trigger/scripting/l4d2_tank_trigger.sp -o build/l4d2_tank_trigger.smx -i ./Multi-Colors/addons/sourcemod/scripting/include